name: Tests unitaires

on: [push, pull_request]

jobs:
  test-anomaly-detector:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./anomaly-detector
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt pytest
      - run: pytest -v

  test-llm-log-analyzer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./llm-log-analyzer
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt pytest
      - run: pytest -v

  test-rca-module:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rca-module
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt pytest
      - run: PYTHONPATH=. pytest -v